"""
map_acts.py code takes the SWBD-DAMSL annotations described in the Jurafsky
et al. coder's manual and maps them to the small set described in
Threlkeld & de Ruiter 2022 and also to the subset described in Jurafsky.

The Switchboard corpus has >300 unique dialogue act tags. 176 of these
occur 5 or fewer times, and of the remaining ones, some are transcription
errors or continuations. re-utterizer.py  attempts to correct for the
errors and continuations. This file reduces the problem size by asserting
that speech act in SWBD-DAMSL is a sub-type of some more basic act.

The the SWBD-DAMSL acts have been tagged as %dml annotation by merge.py.
The mapped acts are tagged here as %fun (function) tags.

Currently, the small set is ['statement', 'question', 'command', 'other'].
It is meant to be extensible, so altering this file should be a straightfoward
way to create (in order to test) extensions. The mapping is given by
FUN_MAPPING.

The SWBD-DAMSL schema is a 42-act set described in the online coder's manual.
It is given by SWBD_MAPPING.
"""

import sys
import os

FUN_MAPPING = {"sd": "statement",
               "b": "other",
               "sv": "statement",
               "%": "other",
               "aa": "other",
               "ba": "statement",
               "qy": "question",
               "x": "other",
               "ny": "other",
               "fc": "other",
               "b^r": "other",
               "sd^e": "statement",
               "qw": "question",
               "sd(^q)": "statement",
               "bk": "other",
               "nn": "other",
               "qy^d": "question",
               "h": "statement",
               "bh": "statement",
               "^q": "statement",
               "bf": "statement",
               "sd^t": "statement",
               "aa^r": "other",
               "+@": "other",
               "o": "other",
               "na": "statement",
               "^2": "other",
               "b^m": "other",
               "ad": "command",
               "qo": "question",
               "qh": "statement",
               "^h": "other",
               "qy^g": "statement",
               "o@": "other",
               "ar": "statement",
               "sv(^q)": "statement",
               "ng": "statement",
               "no": "statement",
               "sd^r": "statement",
               "br": "other",
               "sd@": "statement",
               "qr": "question",
               "fp": "other",
               "qrr": "question",
               "ny^r": "other",
               "nd": "statement",
               "sv^t": "statement",
               "nn^r": "other",
               "fe": "statement",
               "fc^m": "other",
               "%@": "other",
               "sv^e": "statement",
               "t3": "other",
               "qy^t": "question",
               "t1": "other",
               "ba^r": "other",
               "bd": "other",
               "^g": "statement",
               "sv^r": "statement",
               "sv@": "statement",
               "qw^d": "question",
               "b@": "other",
               "ft": "other",
               "fa": "statement",
               "aa^m": "other",
               "sd^m": "statement",
               "ad^t": "command",
               "br^m": "other",
               "aap": "other",
               "sd^c": "statement",
               "qw^t": "question",
               "co": "question",
               "x@": "other",
               "sd*": "statement",
               "am": "statement",
               "ar^r": "statement",
               "na^r": "statement",
               "na^m": "statement",
               "cc": "statement",
               '\"': "other",
               "ba@": "statement",
               "bk^r": "other",
               "qy^r": "question",
               "fc^t": "other",
               "sv^m": "statement",
               "+": "other",
               "sv*": "statement",
               "arp": "statement",
               "sd(^q)^t": "statement",
               "qy^h": "question",
               "qy@": "question",
               "bk^m": "statement",
               "aa@": "statement",
               "qy^g^t": "question",
               "by": "statement",
               "fc^r": "other",
               "sd,o@": "statement",
               "qy^m": "question",
               "qy^c": "question",
               "fp^m": "other",
               "qy^d^t": "question",
               "qw^r": "question",
               "qr^d": "question",
               "co^t": "question",
               "qw^h": "question",
               "bc": "other",
               "+*": "other",
               "sd^e^t": "statement",
               "na^t": "statement",
               "qw@": "question",
               "fx": "statement",
               "sv,o@": "statement",
               "sd^e@": "statement",
               "qy^2": "question",
               "bf@": "statement",
               "ny^m": "statement",
               "bd^r": "other",
               "b*": "other",
               "^2@": "other",
               "qy^d^r": "question",
               "qy^d@": "question",
               "qrr^t": "question",
               "qo^t": "question",
               "ny@": "statement",
               "nn^m": "statement",
               "bh^m": "statement",
               "bf^r": "statement",
               "ad(^q)": "command",
               "^q^t": "statement",
               "sv(^q)@": "statement",
               "sd^e^r": "statement",
               "sd^e^m": "statement",
               "sd^2": "statement",
               "qrr^d": "question",
               "o*": "other",
               "nn^e": "other",
               "fo": "other",
               "^2^g": "question",
               "sd(^q)@": "statement",
               "sd(^q)*": "statement",
               "qy^g@": "question",
               "qy^g*": "question",
               "qy^d^m": "question",
               "qy(^q)": "question",
               "qo^d": "question",
               "qh^m": "statement",
               "oo": "question",
               "o^r": "other",
               "no^t": "statement",
               "ng^r": "statement",
               "h^r": "other",
               "ad^r": "command",
               "ad^c": "command",
               "ad@": "command",
               "aa*": "statement",
               "sv^c": "statement",
               "sv^2": "statement",
               "sv,sd,o@": "statement",
               "qy*": "question",
               "qw^g": "question",
               "qw^d^t": "question",
               "qr^t": "question",
               "qh@": "statement",
               "o^c": "other",
               "nd^t": "statement",
               "na@": "statement",
               "fw": "statement",
               "fp^r": "other",
               "co^c": "question",
               "bh^r": "statement",
               "bh@": "statement",
               "bf^m": "statement",
               "ba^m": "statement",
               "b^m^t": "other",
               "aa^t": "statement",
               "aa^2": "statement",
               "^q@": "statement",
               "^q*": "statement",
               "%*": "other",
               "x*": "other",
               "sd^q": "statement",
               "qy^g^r": "question",
               "qy^g^c": "question",
               "qy^d^h": "question",
               "qy^c^r": "question",
               "qw^m": "question",
               "qw^c": "question",
               "qw*": "question",
               "qh^r": "statement",
               "qh^h": "statement",
               "oo^t": "question",
               "o^t": "other",
               "ny^e": "statement",
               "ny^c": "statement",
               "no^r": "other",
               "nn*": "statement",
               "ng^m": "statement",
               "h^t": "other",
               "fc@": "other",
               "fa^c": "statement",
               "cc^r": "statement",
               "br^r": "other",
               "bk@": "other",
               "bf^t": "statement",
               "bf^g": "statement",
               "bf*": "statement",
               "bf(^q)": "statement",
               "bc^r": "other",
               "b^m^r": "other",
               "b^m^g": "statement",
               "b^m@": "statement",
               "am^r": "statement",
               "ad*": "command",
               "aa,o@": "statement",
               "^q^r": "statement",
               "^h^r": "statement",
               "^2*": "other",
               "t1^t": "other",
               "sv^e^r": "statement",
               "sv;sd": "statement",
               "sv,qy^g@": "statement",
               "sv(^q)*": "statement",
               "sd^t*": "statement",
               "sd^r@": "statement",
               "sd^m@": "statement",
               "sd^m*": "statement",
               "sd^e(^q)^r": "statement",
               "sd;sv": "statement",
               "sd;qy^d": "statement",
               "sd;no": "statement",
               "sd,sv": "statement",
               "sd,qy^g": "statement",
               "sd(^q)^r": "statement",
               "qy^h@": "question",
               "qy^d^c": "question",
               "qy^d*": "question",
               "qy^d(^q)": "question",
               "qy,am,o@": "question",
               "qw^t@": "question",
               "qw^r^t": "question",
               "qw^d^m": "question",
               "qw^d^c": "question",
               "qw^d@": "question",
               "qw(^q)": "question",
               "qrr@": "question",
               "qr^d*": "question",
               "qr(^q)": "question",
               "qo^r": "question",
               "qo^d^c": "question",
               "qo@": "question",
               "qh^g": "statement",
               "qh^c": "statement",
               "qh*": "statement",
               "qh(^q)": "statement",
               "oo(^q)": "question",
               "ny^t": "statement",
               "ny^c^r": "statement",
               "ny*": "statement",
               "no@": "statement",
               "nn^t": "statement",
               "nn^r^t": "statement",
               "nn^r@": "statement",
               "ng^t": "statement",
               "ng^r,o@": "statement",
               "na^m^t": "statement",
               "na,sd,o@": "statement",
               "h^m": "statement",
               "h@": "statement",
               "h,sd": "statement",
               "fw*": "statement",
               "ft^t": "other",
               "ft^m": "other",
               "fo^c": "other",
               "fc,o@": "other",
               "fa^t": "statement",
               "fa^r": "statement",
               "cc^t": "statement",
               "br,o@": "other",
               "bk^t": "statement",
               "bk,sd,o@": "statement",
               "bh,sd,o@": "statement",
               "bf^2": "statement",
               "bf,nn,o@": "statement",
               "bd@": "statement",
               "ba^m@": "statement",
               "ba,fe": "statement",
               "b^t": "other",
               "b^r@": "other",
               "b^m,sd,o@": "statement",
               "b^2": "other",
               "ar^m": "statement",
               "ad,qy@": "command",
               "ad,o@": "command",
               "aap^r": "statement",
               "aap^m": "statement",
               "aa^r,o@": "statement",
               "aa^h": "statement",
               "aa,ar": "statement",
               "^h^t": "statement",
               "^h@": "statement",
               "^g@": "question",
               "^2^t": "other",
               "^2^r": "other",
               "%@*": "other",
               "%,o@": "other"}

SWBD_MAPPING = {
    "sd": "sd",
    "b": "b",
    "sv": "sv",
    "%": "%",
    "aa": "aa",
    "ba": "ba",
    "qy": "qy",
    "x": "x",
    "ny": "ny",
    "fc": "fc",
    "b^r": "b",
    "sd^e": "sd",
    "qw": "qw",
    "sd(^q)": "sd",
    "bk": "bk",
    "nn": "nn",
    "qy^d": "qy^d",
    "h": "h",
    "bh": "bh",
    "^q": "^q",
    "bf": "bf",
    "sd^t": "sd",
    "aa^r": "aa",
    "+@": "@",
    "o": "bc",
    "na": "na",
    "^2": "^2",
    "b^m": "b^m",
    "ad": "ad",
    "qo": "qo",
    "qh": "qh",
    "^h": "^h",
    "qy^g": "qy",
    "o@": "bc",
    "ar": "ar",
    "sv(^q)": "sv",
    "ng": "ng",
    "no": "no",
    "sd^r": "sd",
    "br": "br",
    "sd@": "sd",
    "qr": "qy",
    "fp": "fp",
    "qrr": "qrr",
    "ny^r": "ny",
    "nd": "nd",
    "sv^t": "sv",
    "nn^r": "nn",
    "fe": "ba",
    "fc^m": "fc",
    "%@": "%",
    "sv^e": "sv",
    "t3": "t3",
    "qy^t": "qy",
    "t1": "t1",
    "ba^r": "ba",
    "bd": "bd",
    "^g": "^g",
    "sv^r": "sv",
    "sv@": "sv",
    "qw^d": "qw^d",
    "b@": "b",
    "ft": "ft",
    "fa": "fa",
    "aa^m": "aa",
    "sd^m": "sd",
    "ad^t": "ad",
    "br^m": "br",
    "aap": "am",
    "sd^c": "sd",
    "qw^t": "qw",
    "co": "cc",
    "x@": "x",
    "sd*": "sd",
    "am": "am",
    "ar^r": "ar",
    "na^r": "na",
    "na^m": "na",
    "cc": "cc",
    '\"': "bc",
    "ba@": "ba",
    "bk^r": "bk",
    "qy^r": "qy",
    "fc^t": "fc",
    "sv^m": "sv",
    "+": "@",
    "sv*": "sv",
    "arp": "nd",
    "sd(^q)^t": "sd",
    "qy^h": "qy",
    "qy@": "qy",
    "bk^m": "bk",
    "aa@": "aa",
    "qy^g^t": "qy",
    "by": "bc",
    "fc^r": "fc",
    "sd,o@": "sd",
    "qy^m": "qy",
    "qy^c": "qy",
    "fp^m": "fp",
    "qy^d^t": "qy^d",
    "qw^r": "qw",
    "qr^d": "qy",
    "co^t": "cc",
    "qw^h": "qw",
    "bc": "bc",
    "+*": "@",
    "sd^e^t": "sd",
    "na^t": "na",
    "qw@": "qw",
    "fx": "sv",
    "sv,o@": "sv",
    "sd^e@": "sd",
    "qy^2": "qy",
    "bf@": "bf",
    "ny^m": "ny",
    "bd^r": "bd",
    "b*": "b",
    "^2@": "^2",
    "qy^d^r": "qy^d",
    "qy^d@": "qy^d",
    "qrr^t": "qrr",
    "qo^t": "qo",
    "ny@": "ny",
    "nn^m": "nn",
    "bh^m": "bh",
    "bf^r": "bf",
    "ad(^q)": "ad",
    "^q^t": "^q",
    "sv(^q)@": "sv",
    "sd^e^r": "sd",
    "sd^e^m": "sd",
    "sd^2": "sd",
    "qrr^d": "qrr",
    "o*": "bc",
    "nn^e": "ng",
    "fo": "bc",
    "^2^g": "^2",
    "sd(^q)@": "sd",
    "sd(^q)*": "sd",
    "qy^g@": "qy",
    "qy^g*": "qy",
    "qy^d^m": "qy^d",
    "qy(^q)": "qy",
    "qo^d": "qo",
    "qh^m": "qh",
    "oo": "cc",
    "o^r": "bc",
    "no^t": "no",
    "ng^r": "ng",
    "h^r": "h",
    "ad^r": "ad",
    "ad^c": "ad",
    "ad@": "ad",
    "aa*": "aa",
    "sv^c": "sv",
    "sv^2": "sv",
    "sv,sd,o@": "sv",
    "qy*": "qy",
    "qw^g": "qw",
    "qw^d^t": "qw^d",
    "qr^t": "qy",
    "qh@": "qh",
    "o^c": "bc",
    "nd^t": "nd",
    "na@": "na",
    "fw": "bc",
    "fp^r": "fp",
    "co^c": "cc",
    "bh^r": "bh",
    "bh@": "bh",
    "bf^m": "bf",
    "ba^m": "ba",
    "b^m^t": "b^m",
    "aa^t": "aa",
    "aa^2": "aa",
    "^q@": "^q",
    "^q*": "^q",
    "%*": "%",
    "x*": "x",
    "sd^q": "sd",
    "qy^g^r": "qy",
    "qy^g^c": "qy",
    "qy^d^h": "qy^d",
    "qy^c^r": "qy",
    "qw^m": "qw",
    "qw^c": "qw",
    "qw*": "qw",
    "qh^r": "qh",
    "qh^h": "qh",
    "oo^t": "cc",
    "o^t": "bc",
    "ny^e": "na",
    "ny^c": "ny",
    "no^r": "no",
    "nn*": "nn",
    "ng^m": "ng",
    "h^t": "h",
    "fc@": "fc",
    "fa^c": "fa",
    "cc^r": "cc",
    "br^r": "br",
    "bk@": "bk",
    "bf^t": "bf",
    "bf^g": "bf",
    "bf*": "bf",
    "bf(^q)": "bf",
    "bc^r": "bc",
    "b^m^r": "b^m",
    "b^m^g": "b^m",
    "b^m@": "b^m",
    "am^r": "am",
    "ad*": "ad",
    "aa,o@": "aa",
    "^q^r": "^q",
    "^h^r": "^h",
    "^2*": "^2",
    "t1^t": "t1",
    "sv^e^r": "sv",
    "sv;sd": "sv",
    "sv,qy^g@": "sv",
    "sv(^q)*": "sv",
    "sd^t*": "sd",
    "sd^r@": "sd",
    "sd^m@": "sd",
    "sd^m*": "sd",
    "sd^e(^q)^r": "sd",
    "sd;sv": "sv",
    "sd;qy^d": "sd",
    "sd;no": "sd",
    "sd,sv": "sv",
    "sd,qy^g": "sd",
    "sd(^q)^r": "sd",
    "qy^h@": "qy",
    "qy^d^c": "qy^d",
    "qy^d*": "qy^d",
    "qy^d(^q)": "qy^d",
    "qy,am,o@": "qy",
    "qw^t@": "qw",
    "qw^r^t": "qw",
    "qw^d^m": "qw^d",
    "qw^d^c": "qw^d",
    "qw^d@": "qw^d",
    "qw(^q)": "qw",
    "qrr@": "qrr",
    "qr^d*": "qy",
    "qr(^q)": "qy",
    "qo^r": "qo",
    "qo^d^c": "qo",
    "qo@": "qo",
    "qh^g": "qh",
    "qh^c": "qh",
    "qh*": "qh",
    "qh(^q)": "qh",
    "oo(^q)": "cc",
    "ny^t": "ny",
    "ny^c^r": "ny",
    "ny*": "ny",
    "no@": "no",
    "nn^t": "nn",
    "nn^r^t": "nn",
    "nn^r@": "nn",
    "ng^t": "ng",
    "ng^r,o@": "ng",
    "na^m^t": "na",
    "na,sd,o@": "na",
    "h^m": "h",
    "h@": "h",
    "h,sd": "h",
    "fw*": "bc",
    "ft^t": "ft",
    "ft^m": "ft",
    "fo^c": "bc",
    "fc,o@": "fc",
    "fa^t": "fa",
    "fa^r": "fa",
    "cc^t": "cc",
    "br,o@": "br",
    "bk^t": "bk",
    "bk,sd,o@": "bk",
    "bh,sd,o@": "bh",
    "bf^2": "bf",
    "bf,nn,o@": "bf",
    "bd@": "bd",
    "ba^m@": "ba",
    "ba,fe": "ba",
    "b^t": "b",
    "b^r@": "b",
    "b^m,sd,o@": "b^m",
    "b^2": "b",
    "ar^m": "ar",
    "ad,qy@": "ad",
    "ad,o@": "ad",
    "aap^r": "am",
    "aap^m": "am",
    "aa^r,o@": "aa",
    "aa^h": "aa",
    "aa,ar": "aa",
    "^h^t": "^h",
    "^h@": "^h",
    "^g@": "^g",
    "^2^t": "^2",
    "^2^r": "^2",
    "%@*": "%",
    "%,o@": "%"}


def map_from_dml(base_dir, file_dir):
    """ Given a list of .cha files, each annotated with a %dml dialogue act,
    overwrite the files with %swb and %fun tags added."""

    file_list = [x for x in os.listdir(base_dir + file_dir) if ".cha" in x]

    total = len(file_list)

    none_errors = 0
    for i, file_name in enumerate(file_list):
        print(f"Updating {i+1} of {total}\t{file_name}")

        with open(base_dir+file_dir+file_name, 'r', encoding="UTF-8") as \
             cha_file:
            lines = cha_file.readlines()

        output = ""
        for line in lines:
            output += line
            if "%dml:" in line:
                damsl_fun = line.split()[1]
                try:
                    swbd_act = SWBD_MAPPING[damsl_fun]
                    output += f"%swb:\t{swbd_act}\n"
                except KeyError:
                    if damsl_fun == "None":
                        output += "%swb:\tNone\n"
                    else:
                        print("%swbd error:")
                        print(file_name)
                        print(line)
                        sys.exit(1)
                try:
                    fun_act = FUN_MAPPING[damsl_fun]
                    output += f"%fun:\t{fun_act}\n"
                except KeyError:
                    if damsl_fun == "None":
                        output += "%fun:\tNone\n"
                        none_errors += 1
                    else:
                        print("%fun error:")
                        print(file_name)
                        print(line)
                        sys.exit(1)

        with open(base_dir+file_dir+file_name, 'w', encoding="UTF-8") as \
             out_file:
            out_file.write(output)

    print(f"None errors:\t{none_errors}")

if __name__ == "__main__":
    map_from_dml("/home/chas/Projects/Speech-Act-Modeling/", "new-sb/")
