#!/bin/sh
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1ec1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1ec2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1ec3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1ec4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1ec5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1ec6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1ec7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1ec8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1nc1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1nc2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1nc3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1nc4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1nc5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1nc6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1nc7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q1nc8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2ec1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2ec2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2ec3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2ec4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2ec5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2ec6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2ec7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2ec8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2nc1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2nc2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2nc3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2nc4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2nc5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2nc6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2nc7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q2nc8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3ec1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3ec2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3ec3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3ec4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3ec5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3ec6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3ec7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3ec8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3nc1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3nc2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3nc3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3nc4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3nc5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3nc6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3nc7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q3nc8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4ec1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4ec2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4ec3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4ec4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4ec5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4ec6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4ec7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4ec8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4nc1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4nc2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4nc3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4nc4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4nc5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4nc6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4nc7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q4nc8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5ec1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5ec2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5ec3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5ec4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5ec5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5ec6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5ec7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5ec8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5nc1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5nc2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5nc3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5nc4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5nc5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5nc6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5nc7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q5nc8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6ec1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6ec2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6ec3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6ec4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6ec5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6ec6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6ec7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6ec8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6nc1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6nc2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6nc3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6nc4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6nc5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6nc6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6nc7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q6nc8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7ec1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7ec2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7ec3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7ec4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7ec5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7ec6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7ec7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7ec8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7nc1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7nc2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7nc3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7nc4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7nc5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7nc6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7nc7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q7nc8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8ec1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8ec2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8ec3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8ec4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8ec5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8ec6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8ec7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8ec8.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8nc1.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8nc2.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8nc3.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8nc4.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8nc5.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8nc6.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8nc7.mix.wav
wget    -P signals/dialogues https://groups.inf.ed.ac.uk/maptask/signals/dialogues/q8nc8.mix.wav
wget -P signals https://groups.inf.ed.ac.uk/maptask/download/maptaskBuild-12410-Mon-May-9-2022.manifest.txt
wget -P signals https://groups.inf.ed.ac.uk/maptask/Creative-Commons-Attribution-4.0.txt
